apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: richtest
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: richtest
    spec:
      containers:
      - name: richtest
        image: metalhorse442/richtest:2
        ports: 
        - containerPort: 80