apiVersion: v1
kind: Service
metadata:
  name: richtest-svc
  labels:
    app: richtest
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32123
    protocol: TCP
  selector:
    app: richtest